### ISSUE TITLE
Add support to choose radius in Morgan fingerprint for consistency with ECFP

### ISSUE THREAD

**Issue by himaghna** [himaghna/molSim#92]

**Comment by JacksonBurns** [comment]
May also need to control bit lengths with `n_bits` or similar keyword parameter in call to generating morgan fingerprint in RDKit.

**Comment by himaghna** [comment]
Options for fingerprint_params in config

Morgan fingerprint
------------------
n_bits
radius

Topological fingerprint
-----------------------
min_path
max_path
